import type { Metadata } from "next";
import "./globals.css";
import "@theme-toggles/react/css/Expand.css"
import ThemeProvider from "../Components/ThemeProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-screen flex flex-col transition-all">
        <ThemeProvider>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
